README.md
pom.xml
src/main/java/se/sundsvall/oepintegrator/Application.java
src/main/resources/application.yml

UF-14809: Repo skeleton

---

src/main/java/se/sundsvall/oepintegrator/api/WebMessageResource.java
src/main/java/se/sundsvall/oepintegrator/api/model/webmessage/ExternalReference.java
src/main/java/se/sundsvall/oepintegrator/api/model/webmessage/Sender.java
src/main/java/se/sundsvall/oepintegrator/api/model/webmessage/WebMessageRequest.java
src/main/java/se/sundsvall/oepintegrator/api/validation/ValidExternalReferences.java
src/main/java/se/sundsvall/oepintegrator/api/validation/impl/ValidExternalReferencesConstraintValidator.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/OpeneSoapIntegration.java
src/main/java/se/sundsvall/oepintegrator/service/WebMessageService.java
src/main/java/se/sundsvall/oepintegrator/service/mapper/MessageMapper.java
src/main/java/se/sundsvall/oepintegrator/utility/Constants.java
src/test/java/se/sundsvall/oepintegrator/api/WebMessageResourceFailureTest.java
src/test/java/se/sundsvall/oepintegrator/api/WebMessageResourceTest.java
src/test/java/se/sundsvall/oepintegrator/api/model/webmessage/ExternalReferenceTest.java
src/test/java/se/sundsvall/oepintegrator/api/model/webmessage/SenderTest.java
src/test/java/se/sundsvall/oepintegrator/api/model/webmessage/WebMessageRequestTest.java
src/test/java/se/sundsvall/oepintegrator/api/validation/impl/ValidExternalReferencesConstraintValidatorTest.java
src/test/java/se/sundsvall/oepintegrator/service/WebMessageServiceTest.java
src/test/java/se/sundsvall/oepintegrator/service/mapper/MessageMapperTest.java

UF-14863: Add API resource for sending webmessage

---

src/main/java/se/sundsvall/oepintegrator/api/WebmessageResource.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/OpeneSoapClient.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/OpeneSoapIntegration.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/model/message/ExternalMessage.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/model/message/ExternalMessageAttachment.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/model/message/Messages.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/model/message/Poster.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/model/message/WebmessageMapper.java
src/main/java/se/sundsvall/oepintegrator/service/WebmessageService.java
src/main/java/se/sundsvall/oepintegrator/utility/Constants.java
src/test/java/se/sundsvall/oepintegrator/api/WebmessageResourceTest.java
src/test/java/se/sundsvall/oepintegrator/integration/opene/soap/OpeneSoapIntegrationTest.java
src/test/java/se/sundsvall/oepintegrator/integration/opene/soap/model/message/ExternalMessageAttachmentTest.java
src/test/java/se/sundsvall/oepintegrator/integration/opene/soap/model/message/ExternalMessageTest.java
src/test/java/se/sundsvall/oepintegrator/integration/opene/soap/model/message/MessagesTest.java
src/test/java/se/sundsvall/oepintegrator/integration/opene/soap/model/message/PosterTest.java
src/test/java/se/sundsvall/oepintegrator/integration/opene/soap/model/message/WebmessageMapperTest.java
src/test/java/se/sundsvall/oepintegrator/service/WebmessageServiceTest.java

UF-14938: Add new integrationmethod for fetching webmessages and add servicelayer logic

---

src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/OpeneSoapClient.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/OpeneSoapIntegration.java
src/test/java/se/sundsvall/oepintegrator/integration/opene/soap/OpeneSoapIntegrationTest.java

UF-14879: Added setStatus to OeP integration

---

src/main/java/se/sundsvall/oepintegrator/configuration/SwaggerBeanConfig.java

UF-15201: Add octotet-stream to supported media types so swagger UI is able to send MultiPartFiles

---

src/main/java/se/sundsvall/oepintegrator/api/model/webmessage/Sender.java
src/main/java/se/sundsvall/oepintegrator/api/validation/ValidSender.java
src/main/java/se/sundsvall/oepintegrator/api/validation/impl/ValidSenderConstraintValidator.java
src/test/java/se/sundsvall/oepintegrator/api/WebmessageResourceFailureTest.java
src/test/java/se/sundsvall/oepintegrator/api/model/webmessage/SenderTest.java
src/test/java/se/sundsvall/oepintegrator/api/validation/impl/ValidSenderConstraintValidatorTest.java
src/test/resources/api/openapi.yaml

UF-15284: Added API-changes for addMessageAsOwner

---

pom.xml
src/main/java/se/sundsvall/oepintegrator/integration/party/PartyClient.java
src/main/java/se/sundsvall/oepintegrator/integration/party/configuration/PartyConfiguration.java
src/main/java/se/sundsvall/oepintegrator/integration/party/configuration/PartyProperties.java
src/main/resources/application-it.yml
src/main/resources/application-junit.yml
src/main/resources/application.yml
src/main/resources/integrations/party/party-api.yaml
src/test/java/se/sundsvall/oepintegrator/integration/party/configuration/PartyConfigurationTest.java
src/test/java/se/sundsvall/oepintegrator/integration/party/configuration/PartyPropertiesTest.java

UF-15289: Added Party-integration

---

src/integration-test/java/se/sundsvall/oepintegrator/apptest/ConfirmDeliveryIT.java
src/integration-test/resources/ConfirmDeliveryIT/__files/test01_confirmDelivery/mappings/api-oep-confirm-delivery.json
src/integration-test/resources/ConfirmDeliveryIT/__files/test01_confirmDelivery/request.json
src/integration-test/resources/ConfirmDeliveryIT/__files/test01_confirmDelivery/responses/confirm-delivery.xml

UF-14877: Add IT-tests for ConfirmDelivery

---

src/main/java/se/sundsvall/oepintegrator/service/CaseService.java
src/test/java/se/sundsvall/oepintegrator/service/CaseServiceTest.java

UF-15317: CasePdf service layer

---

src/main/java/se/sundsvall/oepintegrator/api/CaseResource.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceFailureTest.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceTest.java
src/test/resources/api/openapi.yaml

UF-15315: add getCasePdf api resource

---

src/main/java/se/sundsvall/oepintegrator/api/CaseResource.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceFailureTest.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceTest.java
src/test/resources/api/openapi.yaml

UF-14934: api resource for get caselist by legalId

---

src/integration-test/java/se/sundsvall/oepintegrator/apptest/WebmessageIT.java
src/main/java/se/sundsvall/oepintegrator/api/WebmessageResource.java
src/test/java/se/sundsvall/oepintegrator/api/WebmessageResourceFailureTest.java
src/test/java/se/sundsvall/oepintegrator/api/WebmessageResourceTest.java
src/test/resources/api/openapi.yaml

UF-15369: Remove unused parameter from getAttachmentById

---

src/main/java/se/sundsvall/oepintegrator/api/model/cases/CaseStatus.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/rest/OpeneRestClient.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/rest/OpeneRestIntegration.java
src/main/java/se/sundsvall/oepintegrator/service/mapper/CaseMapper.java
src/test/java/se/sundsvall/oepintegrator/api/model/cases/CaseStatusTest.java
src/test/java/se/sundsvall/oepintegrator/integration/opene/rest/OpeneRestIntegrationTest.java
src/test/java/se/sundsvall/oepintegrator/service/mapper/CaseMapperTest.java
src/test/resources/mappings/case-status.xml

UF-15366: Add integration method and mapping for caseStatus

---

src/main/java/se/sundsvall/oepintegrator/service/CaseService.java
src/test/java/se/sundsvall/oepintegrator/service/CaseServiceTest.java

 UF-15365: add service layer for getCaseStatus @Cheezi747

---

src/main/java/se/sundsvall/oepintegrator/api/CaseResource.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceFailureTest.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceTest.java
src/test/resources/api/openapi.yaml

 UF-15364: add api resource for getCaseStatus

---

src/main/java/se/sundsvall/oepintegrator/api/CaseResource.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceFailureTest.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceTest.java
src/test/resources/api/openapi.yaml

UF-15359: Add API changes for getCaseAttachment

---

src/main/java/se/sundsvall/oepintegrator/integration/opene/rest/OpeneRestClient.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/rest/OpeneRestIntegration.java
src/test/java/se/sundsvall/oepintegrator/integration/opene/OpeneClientFactoryTest.java
src/test/java/se/sundsvall/oepintegrator/integration/opene/rest/OpeneRestIntegrationTest.java

UF-15361: Add integration changes for getCaseAttachment

---

src/integration-test/java/se/sundsvall/oepintegrator/apptest/CaseIT.java
src/integration-test/resources/CaseIT/__files/test05_getCaseStatus/mappings/api-oep-get-status.json
src/integration-test/resources/CaseIT/__files/test05_getCaseStatus/response.json
src/integration-test/resources/CaseIT/__files/test05_getCaseStatus/responses/get-case-status-response.xml

UF-15367: Add IT-test for get caseStatus

---

src/main/java/se/sundsvall/oepintegrator/api/CaseResource.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/rest/OpeneRestIntegration.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceFailureTest.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceTest.java
src/test/resources/api/openapi.yaml

UF-15573: Fix bugs

---

src/integration-test/resources/WebmessageIT/__files/test01_createWebmessageByAdministratorId/request.json
src/main/java/se/sundsvall/oepintegrator/service/mapper/MessageMapper.java
src/test/java/se/sundsvall/oepintegrator/service/mapper/MessageMapperTest.java

UF-15573: Fixed mapping bug

---

src/main/java/se/sundsvall/oepintegrator/api/CaseResource.java
src/main/java/se/sundsvall/oepintegrator/api/model/cases/Case.java
src/main/java/se/sundsvall/oepintegrator/integration/opene/rest/OpeneRestIntegration.java
src/main/java/se/sundsvall/oepintegrator/service/CaseService.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceFailureTest.java
src/test/java/se/sundsvall/oepintegrator/api/CaseResourceTest.java
src/test/java/se/sundsvall/oepintegrator/api/model/cases/CaseTest.java
src/test/resources/api/openapi.yaml

UF-15909: Add new API-resource to get case

---

src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/configuration/SoapClientFactory.java

UF-16090: change soap encoder encoding to ISO-8859-1

---

src/main/java/se/sundsvall/oepintegrator/integration/opene/soap/OpeneSoapClient.java

UF-16090: revert to UTF-8 and define UTF-8 all the way
